### ISSUE TITLE
SnackBarのデザインの実装

### ISSUE THREAD

**Issue by dao0203** [dao0203/share_study_app#116]
## 目的
- #113 
- 上記にSnackBarを実装している部分があるため、これが終わったら作業を開始する。
- 現在、ログイン処理などでSnackBarを表示するようにしているが、あまりにもシンプルすぎるため、シェアスタにあったデザインを作成して欲しい。

<img src='https://github.com/dao0203/share_study_app/assets/111327327/8f8dfbe4-d3b8-45e2-a5e3-fa4ab2ab6aee' width='300'>

## タスク
- ui/componentsあたりに作成する
- 命名規則は〇〇SnackBar
  - ErrorSnackBar・SuccessSnackBar etc...

**Comment by dao0203** [comment]
どこら辺で迷っとる感じだっけ？

**Comment by Mgtantheta** [comment]
snackbarが表示されないっす

**Comment by dao0203** [comment]
作業中のでもいいので、コードをコミットしてもらえると嬉しいです！

**Comment by Mgtantheta** [comment]
ドラフトの方でしてるよ

2023年10月6日(金) 20:32 Yuya Sato ***@***.***>:

**Comment by dao0203** [comment]
ありがとうございます！
コードの方を見てきたのですが、状況としては質問をポストした時のスナックバー表示がされない感じでしょうか？
もし現状でも分からないことがあったら、明日の夜にやりましょう！眠いです😴
他にもアサインしているissueがありますので、詰まってしまった場合はそちらも同時並行でお願いします！

また、質問する際に現状を教えていただいてとても嬉しいです！
補足で、他に質問する際なこの内容が欲しいなって物を列挙します！
- エラー（もしあれば）
- やってみたこと・試して見た事
- エラー箇の記載・Urlの共有など
  - //ここでエラーが起きている  etc...

今回はコードベース上での問題が多いと感じたので、以上の点を追記していただけますと幸いです！

**Comment by Mgtantheta** [comment]
一応こんな感じで書いてたけど足りなかったらごめんなさい！

2023年10月6日(金) 23:37 Yuya Sato ***@***.***>:
