### ISSUE TITLE
FlutterのDialogを不用意に閉じないようにする

### ISSUE THREAD

**Issue by Mgtantheta** [dao0203/share_study_app#130]
## 目的
- うっかり自分の予想外のタイミングでDialogが閉じることがあり、それを防ぐため。

## タスク
- [FlutterのDialogを不用意に閉じないようにする](https://zenn.dev/suba/articles/cf797ccc680bb9)を参考にalertDialogの箇所を修正

**Comment by dao0203** [comment]
#90 で解決しました！
